const assets = {
  facebookIcon: require('./icons/facebook.png'),
  googleIcon: require('./icons/google.png'),
  introSlider1: require('./images/sliderImage1.png'),
  introSlider2: require('./images/sliderImage2.png'),
  introSlider3: require('./images/sliderImage3.png'),
  whiteBg: require('./images/whiteBg.png'),
  signIn1: require('./images/screen.png'),
  signIn2: require('./images/screen.png'),
  signIn3: require('./images/screen.png'),
  profile: require('./images/humanicon.png'),
  record: require('./images/Mark.png'),
  photoUpload: require('./images/Fill.png'),
  femaleDoctor:  require('./images/femaleDoctor.png'),
  womenChatBot:  require('./images/womantalkingwithchatbot.png'),
  onlineEducation:  require('./images/Onlineeducationonthelaptop.png'),
  homeTab: require('./images/home.png'),
  chatTab: require('./images/chat.png'),
  settingTab: require('./images/setting.png'),
  arrowBack: require('./images/arrowBack.png'),
  dummyImg: require('./images/dummyImage.png'),
  progressTick: require('./images/progressTick.png'),
  whiteArrow: require('./images/whitearrow.png'),
  cardBg: require('./images/cardBg.png'),
  location: require('./images/location.png'),
  codeImg: require('./images/codeImg.png'),
  reactangleChat: require('./images/RectangleChat.png'),
  voiceImg: require('./images/voiceImg.png'),
  videoCover: require('./images/VideoCover.png'),
  youtubeArrow: require('./images/youtubeArrow.png'),
  youtubeEllipse: require('./images/youtubeEllipse.png'),
  logOut: require('./images/exit.png'),
  support: require('./images/support.png'),
  invite: require('./images/follow.png'),
  person: require('./images/user.png'),
  healthRecord: require('./images/medical-record.png'),
  profilePic: require('./images/profilePic.png'),
  imageBorder: require('./images/imageBorger.png'),
  arrow: require('./images/arrow.png'),
  profilePhoto: require('./images/profile.png'),
};

export default assets;
